version: 1
build:
  binary: mirumd
accounts:
- name: main
  coins:
  - 10000000000000000mirum
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: mirum
    evm:
      params:
        evm_denom: mirum
    gov:
      deposit_params:
        min_deposit:
        - amount: "1000000"
          denom: mirum
    mint:
      params:
        mint_denom: mirum
    staking:
      params:
        bond_denom: mirum
  chain_id: terramirum-testnet
validators:
- name: main
  bonded: 100000000000mirum
  home: $HOME/.mirumd